---
title: "Repeated cross-validation with cvms and groupdata2"
author: 
  - "Ludvig Renbo Olsen"
date: "`r Sys.Date()`"
abstract: |
  This vignette shows how to perform repeated cross-validation with cvms and groupdata2.
  &nbsp;  
  UNDER CONSTRUCTION ;)
  &nbsp;  
  Contact author at r-pkgs@ludvigolsen.dk
  &nbsp;  
  &nbsp;  
  
output: 
  rmarkdown::html_vignette:
    css: 
    - !expr system.file("rmarkdown/templates/html_vignette/resources/vignette.css", package = "rmarkdown")
    - styles.css
    fig_width: 6
    fig_height: 4
    toc: yes
    number_sections: no
  rmarkdown::pdf_document:
    highlight: tango
    number_sections: yes
    toc: yes
    toc_depth: 4
vignette: >
  %\VignetteIndexEntry{Repeated_cross_validation_with_cvms_and_groupdata2}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/vignette_repeated-",
  dpi = 92,
  fig.retina = 2
)
```

## Attach packages
```{r warning=FALSE, message=FALSE}
library(cvms)
library(groupdata2) # fold()
library(knitr) # kable()
library(dplyr) # %>% arrange()
library(ggplot2)
```

## Load data


```{r}
data <- Orange
```

## Partition data

```{r}

```

## Basic model

```{r}
summary(lm(circumference ~ age, data=data))
```

## Fold data

```{r}
# Set seed for reproducibility
set.seed(2)

# Fold data 
data <- fold(data, k = 4,
             id_col = 'Tree',
             num_fold_cols = 10,
             handle_existing_fold_cols = "keep")

# Show first 15 rows of data
data %>% head(10) %>% kable()

```

# Repeated cross-validation

```{r}
CV <- cross_validate(data, "circumference ~ age", 
                     fold_cols = paste0(".folds_", 1:9), 
                     family = 'gaussian', 
                     REML = FALSE)

# Show results
CV

# The output now has a nested 'Results' tibble
# Let's see a subset of the columns
CV$Results[[1]] %>% select(1:9) %>% head(10) %>%  kable()
```


```{r}
# Model coefficients
CV_coeffs <- CV$Coefficients[[1]]

CV_coeffs %>% head(10) %>% kable()
```

```{r}
# Coefficient estimate
ggplot(CV_coeffs, aes(x=term, y=estimate, color=term)) +
  geom_jitter()  +
  theme_light()

# P-values
CV_coeffs$p.value <- ifelse(CV_coeffs$p.value < 0.001, 0.001, CV_coeffs$p.value)
CV_coeffs$p.value <- ifelse(CV_coeffs$p.value > 0.2, 0.2, CV_coeffs$p.value)
ggplot(CV_coeffs, aes(x=term, y=p.value, color=term)) +
  geom_jitter() +
  scale_y_log10(breaks = c(0,0.001,0.01,0.05,0.1,0.2),
                labels = c("0","<=0.001","0.01","0.05","0.1",">=0.2")) +
  theme_light()
```
