library(cvms)
context("evaluate_residuals()")

test_that("evaluate_residuals() have expected output", {
  xpectr::set_test_seed(2)

  df <- data.frame("t" = runif(20), "p" = runif(20), "grp" = rep(1:5, 4))

  # xpectr::gxs_function(fn = evaluate_residuals,
  #                      args_values = list(
  #                        data = list(df, dplyr::group_by(df, .data$grp), NA, 2, tibble::tibble()),
  #                        predictions_col = list("p", "t", "k", NA, 2),
  #                        targets_col = list("t", "p", "k", NA, 2),
  #                        metrics = list(list("all" = TRUE), 4, NA)
  #                      ))

  ## Testing 'evaluate_residuals'                                             ####
  ## Initially generated by xpectr
  # Testing different combinations of argument values

  # Testing evaluate_residuals(data = dplyr::group_by(df, ...
  # Assigning output
  output_19816 <- evaluate_residuals(data = dplyr::group_by(df, .data$grp), predictions_col = "p", targets_col = "t", metrics = list(all = TRUE))
  # Testing class
  expect_equal(
    class(output_19816),
    c("tbl_df", "tbl", "data.frame"),
    fixed = TRUE)
  # Testing column values
  expect_equal(
    output_19816[["grp"]],
    c(1, 2, 3, 4, 5),
    tolerance = 1e-4)
  expect_equal(
    output_19816[["RMSE"]],
    c(0.44147, 0.17496, 0.27494, 0.43813, 0.37009),
    tolerance = 1e-4)
  expect_equal(
    output_19816[["MAE"]],
    c(0.42508, 0.13528, 0.21217, 0.35566, 0.29967),
    tolerance = 1e-4)
  expect_equal(
    output_19816[["NRMSE"]],
    c(0.58196, 0.20651, 0.45248, 1.4606, 0.42595),
    tolerance = 1e-4)
  expect_equal(
    output_19816[["RMSEIQR"]],
    c(1.063, 0.31276, 0.94061, 1.60497, 1.13615),
    tolerance = 1e-4)
  expect_equal(
    output_19816[["RMSESTD"]],
    c(1.28827, 0.4406, 1.01305, 2.6853, 1.02785),
    tolerance = 1e-4)
  expect_equal(
    output_19816[["RMSLE"]],
    c(0.31106, 0.11261, 0.17139, 0.281, 0.24654),
    tolerance = 1e-4)
  expect_equal(
    output_19816[["MALE"]],
    c(0.29118, 0.08826, 0.13266, 0.22696, 0.20577),
    tolerance = 1e-4)
  expect_equal(
    output_19816[["RAE"]],
    c(1.60489, 0.41285, 1.06777, 2.5226, 1.18263),
    tolerance = 1e-4)
  expect_equal(
    output_19816[["RSE"]],
    c(2.21285, 0.25884, 1.36835, 9.61444, 1.40864),
    tolerance = 1e-4)
  expect_equal(
    output_19816[["RRSE"]],
    c(1.48757, 0.50876, 1.16977, 3.10072, 1.18686),
    tolerance = 1e-4)
  expect_equal(
    output_19816[["MAPE"]],
    c(1.0771, 0.26243, 0.33952, 1.36661, 0.66679),
    tolerance = 1e-4)
  expect_equal(
    output_19816[["MSE"]],
    c(0.19489, 0.03061, 0.07559, 0.19196, 0.13697),
    tolerance = 1e-4)
  expect_equal(
    output_19816[["TAE"]],
    c(1.70033, 0.54113, 0.84867, 1.42263, 1.19867),
    tolerance = 1e-4)
  expect_equal(
    output_19816[["TSE"]],
    c(0.77958, 0.12245, 0.30236, 0.76783, 0.54787),
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    names(output_19816),
    c("grp", "RMSE", "MAE", "NRMSE", "RMSEIQR", "RMSESTD", "RMSLE",
      "MALE", "RAE", "RSE", "RRSE", "MAPE", "MSE", "TAE", "TSE"),
    fixed = TRUE)
  # Testing column classes
  expect_equal(
    xpectr::element_classes(output_19816),
    c("integer", "numeric", "numeric", "numeric", "numeric", "numeric",
      "numeric", "numeric", "numeric", "numeric", "numeric", "numeric",
      "numeric", "numeric", "numeric"),
    fixed = TRUE)
  # Testing column types
  expect_equal(
    xpectr::element_types(output_19816),
    c("integer", "double", "double", "double", "double", "double", "double",
      "double", "double", "double", "double", "double", "double",
      "double", "double"),
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(output_19816),
    c(5L, 15L))
  # Testing group keys
  expect_equal(
    colnames(dplyr::group_keys(output_19816)),
    character(0),
    fixed = TRUE)

  # Testing evaluate_residuals(data = df, predictions_col ...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(evaluate_residuals(data = df, predictions_col = "p", targets_col = "k", metrics = list(all = TRUE))),
    xpectr::strip("Assertion on 'colnames(data)' failed: Must include the elements {p,k}."),
    fixed = TRUE)

  # Testing evaluate_residuals(data = df, predictions_col ...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(evaluate_residuals(data = df, predictions_col = "p", targets_col = NA, metrics = list(all = TRUE))),
    xpectr::strip("1 assertions failed:\n * Variable 'targets_col': May not be NA."),
    fixed = TRUE)

  # Testing evaluate_residuals(data = df, predictions_col ...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(evaluate_residuals(data = df, predictions_col = "p", targets_col = 2, metrics = list(all = TRUE))),
    xpectr::strip(paste0("1 assertions failed:\n * Variable 'targets_col': Must be of ",
           "type 'string', not 'double'.")),
    fixed = TRUE)

  # Testing evaluate_residuals(data = df, predictions_col ...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(evaluate_residuals(data = df, predictions_col = "p", targets_col = "t", metrics = 4)),
    xpectr::strip(paste0("1 assertions failed:\n * Variable 'metrics': Must be of type",
           " 'list', not 'double'.")),
    fixed = TRUE)

  # Testing evaluate_residuals(data = df, predictions_col ...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(evaluate_residuals(data = df, predictions_col = "p", targets_col = "t", metrics = NA)),
    xpectr::strip(paste0("1 assertions failed:\n * Variable 'metrics': Must be of type",
           " 'list', not 'logical'.")),
    fixed = TRUE)

  # Testing evaluate_residuals(data = NA, predictions_col ...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(evaluate_residuals(data = NA, predictions_col = "p", targets_col = "t", metrics = list(all = TRUE))),
    xpectr::strip(paste0("1 assertions failed:\n * Variable 'data': Must be of type 'd",
           "ata.frame', not 'logical'.")),
    fixed = TRUE)

  # Testing evaluate_residuals(data = 2, predictions_col =...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(evaluate_residuals(data = 2, predictions_col = "p", targets_col = "t", metrics = list(all = TRUE))),
    xpectr::strip(paste0("1 assertions failed:\n * Variable 'data': Must be of type 'd",
           "ata.frame', not 'double'.")),
    fixed = TRUE)

  # Testing evaluate_residuals(data = tibble::tibble(), pr...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(evaluate_residuals(data = tibble::tibble(), predictions_col = "p", targets_col = "t", metrics = list(all = TRUE))),
    xpectr::strip(paste0("1 assertions failed:\n * Variable 'data': Must have at least",
           " 1 rows, but has 0 rows.")),
    fixed = TRUE)

  # Testing evaluate_residuals(data = df, predictions_col ...
  # Assigning output
  output_12969 <- evaluate_residuals(data = df, predictions_col = "t", targets_col = "t", metrics = list(all = TRUE))
  # Testing class
  expect_equal(
    class(output_12969),
    c("tbl_df", "tbl", "data.frame"),
    fixed = TRUE)
  # Testing column values
  expect_equal(
    output_12969[["RMSE"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_12969[["MAE"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_12969[["NRMSE"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_12969[["RMSEIQR"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_12969[["RMSESTD"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_12969[["RMSLE"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_12969[["MALE"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_12969[["RAE"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_12969[["RSE"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_12969[["RRSE"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_12969[["MAPE"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_12969[["MSE"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_12969[["TAE"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_12969[["TSE"]],
    0,
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    names(output_12969),
    c("RMSE", "MAE", "NRMSE", "RMSEIQR", "RMSESTD", "RMSLE", "MALE",
      "RAE", "RSE", "RRSE", "MAPE", "MSE", "TAE", "TSE"),
    fixed = TRUE)
  # Testing column classes
  expect_equal(
    xpectr::element_classes(output_12969),
    c("numeric", "numeric", "numeric", "numeric", "numeric", "numeric",
      "numeric", "numeric", "numeric", "numeric", "numeric", "numeric",
      "numeric", "numeric"),
    fixed = TRUE)
  # Testing column types
  expect_equal(
    xpectr::element_types(output_12969),
    c("double", "double", "double", "double", "double", "double", "double",
      "double", "double", "double", "double", "double", "double",
      "double"),
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(output_12969),
    c(1L, 14L))
  # Testing group keys
  expect_equal(
    colnames(dplyr::group_keys(output_12969)),
    character(0),
    fixed = TRUE)

  # Testing evaluate_residuals(data = df, predictions_col ...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(evaluate_residuals(data = df, predictions_col = "k", targets_col = "t", metrics = list(all = TRUE))),
    xpectr::strip("Assertion on 'colnames(data)' failed: Must include the elements {k,t}."),
    fixed = TRUE)

  # Testing evaluate_residuals(data = df, predictions_col ...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(evaluate_residuals(data = df, predictions_col = NA, targets_col = "t", metrics = list(all = TRUE))),
    xpectr::strip("1 assertions failed:\n * Variable 'predictions_col': May not be NA."),
    fixed = TRUE)

  # Testing evaluate_residuals(data = df, predictions_col ...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(evaluate_residuals(data = df, predictions_col = 2, targets_col = "t", metrics = list(all = TRUE))),
    xpectr::strip(paste0("1 assertions failed:\n * Variable 'predictions_col': Must be",
           " of type 'string', not 'double'.")),
    fixed = TRUE)

  # Testing evaluate_residuals(data = df, predictions_col ...
  # Assigning output
  output_11150 <- evaluate_residuals(data = df, predictions_col = "p", targets_col = "p", metrics = list(all = TRUE))
  # Testing class
  expect_equal(
    class(output_11150),
    c("tbl_df", "tbl", "data.frame"),
    fixed = TRUE)
  # Testing column values
  expect_equal(
    output_11150[["RMSE"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_11150[["MAE"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_11150[["NRMSE"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_11150[["RMSEIQR"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_11150[["RMSESTD"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_11150[["RMSLE"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_11150[["MALE"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_11150[["RAE"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_11150[["RSE"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_11150[["RRSE"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_11150[["MAPE"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_11150[["MSE"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_11150[["TAE"]],
    0,
    tolerance = 1e-4)
  expect_equal(
    output_11150[["TSE"]],
    0,
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    names(output_11150),
    c("RMSE", "MAE", "NRMSE", "RMSEIQR", "RMSESTD", "RMSLE", "MALE",
      "RAE", "RSE", "RRSE", "MAPE", "MSE", "TAE", "TSE"),
    fixed = TRUE)
  # Testing column classes
  expect_equal(
    xpectr::element_classes(output_11150),
    c("numeric", "numeric", "numeric", "numeric", "numeric", "numeric",
      "numeric", "numeric", "numeric", "numeric", "numeric", "numeric",
      "numeric", "numeric"),
    fixed = TRUE)
  # Testing column types
  expect_equal(
    xpectr::element_types(output_11150),
    c("double", "double", "double", "double", "double", "double", "double",
      "double", "double", "double", "double", "double", "double",
      "double"),
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(output_11150),
    c(1L, 14L))
  # Testing group keys
  expect_equal(
    colnames(dplyr::group_keys(output_11150)),
    character(0),
    fixed = TRUE)

  # Testing evaluate_residuals(data = NULL, predictions_co...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(evaluate_residuals(data = NULL, predictions_col = "p", targets_col = "t", metrics = list(all = TRUE))),
    xpectr::strip(paste0("1 assertions failed:\n * Variable 'data': Must be of type 'd",
           "ata.frame', not 'NULL'.")),
    fixed = TRUE)

  # Testing evaluate_residuals(data = df, predictions_col ...
  # Assigning output
  output_11631 <- evaluate_residuals(data = df, predictions_col = "p", targets_col = "t", metrics = list(all = TRUE))
  # Testing class
  expect_equal(
    class(output_11631),
    c("tbl_df", "tbl", "data.frame"),
    fixed = TRUE)
  # Testing column values
  expect_equal(
    output_11631[["RMSE"]],
    0.35497,
    tolerance = 1e-4)
  expect_equal(
    output_11631[["MAE"]],
    0.28557,
    tolerance = 1e-4)
  expect_equal(
    output_11631[["NRMSE"]],
    0.39379,
    tolerance = 1e-4)
  expect_equal(
    output_11631[["RMSEIQR"]],
    0.63032,
    tolerance = 1e-4)
  expect_equal(
    output_11631[["RMSESTD"]],
    1.16632,
    tolerance = 1e-4)
  expect_equal(
    output_11631[["RMSLE"]],
    0.23603,
    tolerance = 1e-4)
  expect_equal(
    output_11631[["MALE"]],
    0.18896,
    tolerance = 1e-4)
  expect_equal(
    output_11631[["RAE"]],
    1.10497,
    tolerance = 1e-4)
  expect_equal(
    output_11631[["RSE"]],
    1.43189,
    tolerance = 1e-4)
  expect_equal(
    output_11631[["RRSE"]],
    1.19661,
    tolerance = 1e-4)
  expect_equal(
    output_11631[["MAPE"]],
    0.74249,
    tolerance = 1e-4)
  expect_equal(
    output_11631[["MSE"]],
    0.126,
    tolerance = 1e-4)
  expect_equal(
    output_11631[["TAE"]],
    5.71144,
    tolerance = 1e-4)
  expect_equal(
    output_11631[["TSE"]],
    2.52009,
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    names(output_11631),
    c("RMSE", "MAE", "NRMSE", "RMSEIQR", "RMSESTD", "RMSLE", "MALE",
      "RAE", "RSE", "RRSE", "MAPE", "MSE", "TAE", "TSE"),
    fixed = TRUE)
  # Testing column classes
  expect_equal(
    xpectr::element_classes(output_11631),
    c("numeric", "numeric", "numeric", "numeric", "numeric", "numeric",
      "numeric", "numeric", "numeric", "numeric", "numeric", "numeric",
      "numeric", "numeric"),
    fixed = TRUE)
  # Testing column types
  expect_equal(
    xpectr::element_types(output_11631),
    c("double", "double", "double", "double", "double", "double", "double",
      "double", "double", "double", "double", "double", "double",
      "double"),
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(output_11631),
    c(1L, 14L))
  # Testing group keys
  expect_equal(
    colnames(dplyr::group_keys(output_11631)),
    character(0),
    fixed = TRUE)

  # Testing evaluate_residuals(data = df, predictions_col ...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(evaluate_residuals(data = df, predictions_col = "p", targets_col = "t", metrics = NULL)),
    xpectr::strip(paste0("1 assertions failed:\n * Variable 'metrics': Must be of type",
           " 'list', not 'NULL'.")),
    fixed = TRUE)

  # Testing evaluate_residuals(data = df, predictions_col ...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(evaluate_residuals(data = df, predictions_col = NULL, targets_col = "t", metrics = list(all = TRUE))),
    xpectr::strip(paste0("1 assertions failed:\n * Variable 'predictions_col': Must be",
           " of type 'string', not 'NULL'.")),
    fixed = TRUE)

  # Testing evaluate_residuals(data = df, predictions_col ...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(evaluate_residuals(data = df, predictions_col = "p", targets_col = NULL, metrics = list(all = TRUE))),
    xpectr::strip(paste0("1 assertions failed:\n * Variable 'targets_col': Must be of ",
           "type 'string', not 'NULL'.")),
    fixed = TRUE)

  ## Finished testing 'evaluate_residuals'                                    ####



})

test_that("evaluate_residuals() have expected output", {
  xpectr::set_test_seed(1)

  df <- data.frame("t" = runif(20), "p" = runif(20), "grp" = rep(1:5, 4))

  ungrouped_res <- evaluate_residuals(
    df, "p", "t",
    metrics = "all"
  )

  expect_equal(
    colnames(ungrouped_res),
    c(
      "RMSE", "MAE", "NRMSE", "RMSEIQR", "RMSESTD",
      "RMSLE", "MALE", "RAE", "RSE", "RRSE",
      "MAPE", "MSE", "TAE", "TSE"
    )
  )
  expect_equal(ungrouped_res$RMSE, 0.4383415, tolerance = 1e-5)
  expect_equal(ungrouped_res$MAE, 0.3493256, tolerance = 1e-5)
  expect_equal(ungrouped_res$NRMSE, 0.4712743, tolerance = 1e-5)
  expect_equal(ungrouped_res$RMSEIQR, 1.028314, tolerance = 1e-5)
  expect_equal(ungrouped_res$RMSESTD, 1.532031, tolerance = 1e-5)
  expect_equal(ungrouped_res$RMSLE, 0.2955423, tolerance = 1e-5)
  expect_equal(ungrouped_res$MALE, 0.2355741, tolerance = 1e-5)
  expect_equal(ungrouped_res$RAE, 1.425217, tolerance = 1e-5)
  expect_equal(ungrouped_res$RSE, 2.470652, tolerance = 1e-5)
  expect_equal(ungrouped_res$RRSE, 1.571831, tolerance = 1e-5)
  expect_equal(ungrouped_res$MAPE, 0.9233602, tolerance = 1e-5)
  expect_equal(ungrouped_res$MSE, 0.1921433, tolerance = 1e-5)
  expect_equal(ungrouped_res$TAE, 6.986512, tolerance = 1e-5)
  expect_equal(ungrouped_res$TSE, 3.842867, tolerance = 1e-5)

  grouped_res <- evaluate_residuals(
    df %>% dplyr::group_by(grp),
    "p", "t",
    metrics = "all"
  )

  expect_equal(
    colnames(grouped_res),
    c(
      "grp", "RMSE", "MAE", "NRMSE", "RMSEIQR", "RMSESTD",
      "RMSLE", "MALE", "RAE", "RSE",
      "RRSE", "MAPE", "MSE", "TAE", "TSE"
    )
  )
  expect_equal(grouped_res$RMSE,
    c(
      0.451565647616432, 0.519060010936869, 0.475013011667194, 0.454888553611741,
      0.234138573611605
    ),
    tolerance = 1e-5
  )
  expect_equal(grouped_res$MAE,
    c(
      0.407086299266666, 0.397724184789695, 0.358668561675586, 0.391197844815906,
      0.191951038548723
    ),
    tolerance = 1e-5
  )
  expect_equal(grouped_res$NRMSE,
    c(
      0.652160302469174, 0.675755108193839, 1.1335399485195, 0.861249796972752,
      0.327165018103644
    ),
    tolerance = 1e-5
  )
  expect_equal(grouped_res$RMSEIQR,
    c(
      1.30041734700364, 1.15052496357359, 3.81745140187305, 1.44042831439479,
      0.386983932227589
    ),
    tolerance = 1e-5
  )
  expect_equal(grouped_res$RMSESTD,
    c(
      1.43814486544896, 1.50905226589782, 2.60289783098973, 1.81516488970619,
      0.624379332243931
    ),
    tolerance = 1e-5
  )
  expect_equal(grouped_res$RMSLE,
    c(
      0.2886413430748, 0.366211402088592, 0.314237354222149, 0.304503365190871,
      0.166835911010467
    ),
    tolerance = 1e-5
  )
  expect_equal(grouped_res$MALE,
    c(
      0.263279042673231, 0.281636667412819, 0.235196273801541, 0.260569609060969,
      0.137188700334378
    ),
    tolerance = 1e-5
  )
  expect_equal(grouped_res$RAE,
    c(
      1.76112392170928, 1.42859014846979, 2.71964745212324, 2.02383072091832,
      0.598062880532025
    ),
    tolerance = 1e-5
  )
  expect_equal(grouped_res$RSE,
    c(
      2.75768087202294, 3.03631832161513, 9.03343615809475, 4.39309810242944,
      0.51979940071117
    ),
    tolerance = 1e-5
  )
  expect_equal(grouped_res$RRSE,
    c(
      1.66062665040127, 1.74250346387464, 3.00556752679003, 2.09597187539085,
      0.720971151094945
    ),
    tolerance = 1e-5
  )
  expect_equal(grouped_res$MAPE,
    c(
      1.19356123357169, 0.979598260014201, 0.432928785595697, 0.665919069119316,
      1.34479362791513
    ),
    tolerance = 1e-5
  )
  expect_equal(grouped_res$MSE,
    c(
      0.203911534107247, 0.269423294953783, 0.225637361253137, 0.206923596206982,
      0.0548208716528769
    ),
    tolerance = 1e-5
  )
  expect_equal(grouped_res$TAE,
    c(
      1.62834519706666, 1.59089673915878, 1.43467424670234, 1.56479137926362,
      0.767804154194891
    ),
    tolerance = 1e-5
  )
  expect_equal(grouped_res$TSE,
    c(
      0.815646136428989, 1.07769317981513, 0.90254944501255, 0.827694384827926,
      0.219283486611508
    ),
    tolerance = 1e-5
  )
})

test_that("call_evaluate_residuals() creates NA results correcly", {
  xpectr::set_test_seed(1)

  df <- data.frame("t" = runif(20), "p" = runif(20), "grp" = rep(1:5, 4))

  na_tibble <- tibble::tibble(
    "grp" = 1:5,
    "RMSE" = NA,
    "MAE" = NA,
    "TSE" = NA,
    "NRMSE" = NA,
    "RMSEIQR" = NA
  )

  expect_equal(
    call_evaluate_residuals(
      df, "p", "t",
      metrics = c("RMSE", "MAE", "TSE", "NRMSE", "RMSEIQR"),
      return_nas = TRUE
    ),
    na_tibble[1, 2:6]
  )

  expect_equal(
    call_evaluate_residuals(
      df %>% dplyr::group_by(grp),
      "p", "t",
      metrics = c("RMSE", "MAE", "TSE", "NRMSE", "RMSEIQR"),
      return_nas = TRUE
    ),
    na_tibble
  )
})
