library(cvms)
context("choosing metrics")

test_that("gaussian_metrics()", {

  # Load data and fold it
  xpectr::set_test_seed(1)

  get_metric_names <- function(...){
    set_metrics("gaussian", metrics_list = gaussian_metrics(...),
                include_model_object_metrics = TRUE)
  }

  # xpectr::gxs_function(fn = get_metric_names,
  #                      args_values = list(
  #                        all = list(NULL,FALSE, TRUE, NA, 1, 0, "hej", list(FALSE)),
  #                        rmse = list(FALSE, TRUE, NA),
  #                        male = list(FALSE, TRUE, NA)
  #                      ), indentation = 2)

  ## Testing 'get_metric_names'                                               ####
  ## Initially generated by xpectr
  # Testing different combinations of argument values

  # Testing get_metric_names(all = FALSE, rmse = FALSE, ma...
  # Assigning output
  output_16327 <- get_metric_names(all = FALSE, rmse = FALSE, male = FALSE)
  # Testing class
  expect_equal(
    class(output_16327),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_16327,
    type = "character")
  # Testing values
  expect_equal(
    output_16327,
    character(0),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_16327),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_16327),
    0L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_16327)),
    0L)

  # Testing get_metric_names(all = NULL, rmse = FALSE, mal...
  # Assigning output
  output_17696 <- get_metric_names(all = NULL, rmse = FALSE, male = TRUE)
  # Testing class
  expect_equal(
    class(output_17696),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_17696,
    type = "character")
  # Testing values
  expect_equal(
    output_17696,
    c("MAE", "RMSLE", "MALE"),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_17696),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_17696),
    3L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_17696)),
    3L)

  # Testing get_metric_names(all = NULL, rmse = FALSE, mal...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(get_metric_names(all = NULL, rmse = FALSE, male = NA)),
    xpectr::strip("Assertion on 'male' failed: May not be NA."),
    fixed = TRUE)

  # Testing get_metric_names(all = TRUE, rmse = FALSE, mal...
  # Assigning output
  output_12293 <- get_metric_names(all = TRUE, rmse = FALSE, male = FALSE)
  # Testing class
  expect_equal(
    class(output_12293),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_12293,
    type = "character")
  # Testing values
  expect_equal(
    output_12293,
    c("MAE", "NRMSE", "RMSEIQR", "RMSESTD", "RMSLE", "RAE", "RSE",
      "RRSE", "MAPE", "MSE", "TAE", "TSE", "r2m", "r2c", "AIC",
      "AICc", "BIC"),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_12293),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_12293),
    17L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_12293)),
    17L)

  # Testing get_metric_names(all = NA, rmse = FALSE, male ...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(get_metric_names(all = NA, rmse = FALSE, male = FALSE)),
    xpectr::strip("Assertion on 'all' failed: May not be NA."),
    fixed = TRUE)

  # Testing get_metric_names(all = 1, rmse = FALSE, male =...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(get_metric_names(all = 1, rmse = FALSE, male = FALSE)),
    xpectr::strip(paste0("Assertion on 'all' failed: Must be of type 'logical flag' (o",
           "r 'NULL'), not 'double'.")),
    fixed = TRUE)

  # Testing get_metric_names(all = 0, rmse = FALSE, male =...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(get_metric_names(all = 0, rmse = FALSE, male = FALSE)),
    xpectr::strip(paste0("Assertion on 'all' failed: Must be of type 'logical flag' (o",
           "r 'NULL'), not 'double'.")),
    fixed = TRUE)

  # Testing get_metric_names(all = "hej", rmse = FALSE, ma...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(get_metric_names(all = "hej", rmse = FALSE, male = FALSE)),
    xpectr::strip(paste0("Assertion on 'all' failed: Must be of type 'logical flag' (o",
           "r 'NULL'), not 'character'.")),
    fixed = TRUE)

  # Testing get_metric_names(all = list(FALSE), rmse = FAL...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(get_metric_names(all = list(FALSE), rmse = FALSE, male = FALSE)),
    xpectr::strip(paste0("Assertion on 'all' failed: Must be of type 'logical flag' (o",
           "r 'NULL'), not 'list'.")),
    fixed = TRUE)

  # Testing get_metric_names(all = NULL, rmse = TRUE, male...
  # Assigning output
  output_13296 <- get_metric_names(all = NULL, rmse = TRUE, male = FALSE)
  # Testing class
  expect_equal(
    class(output_13296),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_13296,
    type = "character")
  # Testing values
  expect_equal(
    output_13296,
    c("RMSE", "MAE", "RMSLE"),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_13296),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_13296),
    3L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_13296)),
    3L)

  # Testing get_metric_names(all = NULL, rmse = NA, male =...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(get_metric_names(all = NULL, rmse = NA, male = FALSE)),
    xpectr::strip("Assertion on 'rmse' failed: May not be NA."),
    fixed = TRUE)

  # Testing get_metric_names(all = NULL, rmse = FALSE, mal...
  # Assigning output
  output_15436 <- get_metric_names(all = NULL, rmse = FALSE, male = FALSE)
  # Testing class
  expect_equal(
    class(output_15436),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_15436,
    type = "character")
  # Testing values
  expect_equal(
    output_15436,
    c("MAE", "RMSLE"),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_15436),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_15436),
    2L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_15436)),
    2L)

  # Testing get_metric_names(all = NULL, rmse = FALSE, mal...
  # Assigning output
  output_15977 <- get_metric_names(all = NULL, rmse = FALSE, male = NULL)
  # Testing class
  expect_equal(
    class(output_15977),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_15977,
    type = "character")
  # Testing values
  expect_equal(
    output_15977,
    c("MAE", "RMSLE"),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_15977),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_15977),
    2L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_15977)),
    2L)

  # Testing get_metric_names(all = NULL, rmse = NULL, male...
  # Assigning output
  output_15700 <- get_metric_names(all = NULL, rmse = NULL, male = FALSE)
  # Testing class
  expect_equal(
    class(output_15700),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_15700,
    type = "character")
  # Testing values
  expect_equal(
    output_15700,
    c("RMSE", "MAE", "RMSLE"),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_15700),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_15700),
    3L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_15700)),
    3L)

  ## Finished testing 'get_metric_names'                                      ####



  ## Testing 'get_metric_names(all = TRUE)'                                 ####
  ## Initially generated by xpectr
  # Assigning output
  output_19662 <- get_metric_names(all = TRUE)
  # Testing class
  expect_equal(
    class(output_19662),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_19662,
    type = "character")
  # Testing values
  expect_equal(
    output_19662,
    c("RMSE", "MAE", "NRMSE", "RMSEIQR", "RMSESTD", "RMSLE", "MALE",
      "RAE", "RSE", "RRSE", "MAPE", "MSE", "TAE", "TSE", "r2m",
      "r2c", "AIC", "AICc", "BIC"),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_19662),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_19662),
    19L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_19662)),
    19L)
  ## Finished testing 'get_metric_names(all = TRUE)'                        ####


})

test_that("binomial_metrics()", {

  # Load data and fold it
  xpectr::set_test_seed(1)

  get_metric_names <- function(...){
    set_metrics("binomial", metrics_list = binomial_metrics(...),
                include_model_object_metrics = TRUE)
  }

  # xpectr::gxs_function(fn = get_metric_names,
  #                      args_values = list(
  #                        all = list(NULL,FALSE, TRUE, NA, 1, 0, "hej", list(FALSE)),
  #                        accuracy = list(FALSE, TRUE, NA),
  #                        f1 = list(FALSE, TRUE, NA)
  #                      ), indentation = 2)

  ## Testing 'get_metric_names'                                               ####
  ## Initially generated by xpectr
  # Testing different combinations of argument values

  # Testing get_metric_names(all = FALSE, accuracy = FALSE...
  # Assigning output
  output_12654 <- get_metric_names(all = FALSE, accuracy = FALSE, f1 = FALSE)
  # Testing class
  expect_equal(
    class(output_12654),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_12654,
    type = "character")
  # Testing values
  expect_equal(
    output_12654,
    character(0),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_12654),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_12654),
    0L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_12654)),
    0L)

  # Testing get_metric_names(all = NULL, accuracy = FALSE,...
  # Assigning output
  output_13720 <- get_metric_names(all = NULL, accuracy = FALSE, f1 = TRUE)
  # Testing class
  expect_equal(
    class(output_13720),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_13720,
    type = "character")
  # Testing values
  expect_equal(
    output_13720,
    c("Balanced Accuracy", "F1", "Sensitivity", "Specificity", "Pos Pred Value",
      "Neg Pred Value", "AUC", "Lower CI", "Upper CI", "Kappa",
      "MCC", "Detection Rate", "Detection Prevalence", "Prevalence"),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_13720),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_13720),
    14L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_13720)),
    14L)

  # Testing get_metric_names(all = NULL, accuracy = FALSE,...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(get_metric_names(all = NULL, accuracy = FALSE, f1 = NA)),
    xpectr::strip("Assertion on 'f1' failed: May not be NA."),
    fixed = TRUE)

  # Testing get_metric_names(all = TRUE, accuracy = FALSE,...
  # Assigning output
  output_15727 <- get_metric_names(all = TRUE, accuracy = FALSE, f1 = FALSE)
  # Testing class
  expect_equal(
    class(output_15727),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_15727,
    type = "character")
  # Testing values
  expect_equal(
    output_15727,
    c("Balanced Accuracy", "Sensitivity", "Specificity", "Pos Pred Value",
      "Neg Pred Value", "AUC", "Lower CI", "Upper CI", "Kappa",
      "MCC", "Detection Rate", "Detection Prevalence", "Prevalence",
      "False Neg Rate", "False Pos Rate", "False Discovery Rate",
      "False Omission Rate", "Threat Score", "AIC", "AICc", "BIC"),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_15727),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_15727),
    21L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_15727)),
    21L)

  # Testing get_metric_names(all = NA, accuracy = FALSE, f...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(get_metric_names(all = NA, accuracy = FALSE, f1 = FALSE)),
    xpectr::strip("Assertion on 'all' failed: May not be NA."),
    fixed = TRUE)

  # Testing get_metric_names(all = 1, accuracy = FALSE, f1...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(get_metric_names(all = 1, accuracy = FALSE, f1 = FALSE)),
    xpectr::strip(paste0("Assertion on 'all' failed: Must be of type 'logical flag' (o",
           "r 'NULL'), not 'double'.")),
    fixed = TRUE)

  # Testing get_metric_names(all = 0, accuracy = FALSE, f1...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(get_metric_names(all = 0, accuracy = FALSE, f1 = FALSE)),
    xpectr::strip(paste0("Assertion on 'all' failed: Must be of type 'logical flag' (o",
           "r 'NULL'), not 'double'.")),
    fixed = TRUE)

  # Testing get_metric_names(all = "hej", accuracy = FALSE...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(get_metric_names(all = "hej", accuracy = FALSE, f1 = FALSE)),
    xpectr::strip(paste0("Assertion on 'all' failed: Must be of type 'logical flag' (o",
           "r 'NULL'), not 'character'.")),
    fixed = TRUE)

  # Testing get_metric_names(all = list(FALSE), accuracy =...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(get_metric_names(all = list(FALSE), accuracy = FALSE, f1 = FALSE)),
    xpectr::strip(paste0("Assertion on 'all' failed: Must be of type 'logical flag' (o",
           "r 'NULL'), not 'list'.")),
    fixed = TRUE)

  # Testing get_metric_names(all = NULL, accuracy = TRUE, ...
  # Assigning output
  output_19081 <- get_metric_names(all = NULL, accuracy = TRUE, f1 = FALSE)
  # Testing class
  expect_equal(
    class(output_19081),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_19081,
    type = "character")
  # Testing values
  expect_equal(
    output_19081,
    c("Balanced Accuracy", "Accuracy", "Sensitivity", "Specificity",
      "Pos Pred Value", "Neg Pred Value", "AUC", "Lower CI", "Upper CI",
      "Kappa", "MCC", "Detection Rate", "Detection Prevalence",
      "Prevalence"),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_19081),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_19081),
    14L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_19081)),
    14L)

  # Testing get_metric_names(all = NULL, accuracy = NA, f1...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(get_metric_names(all = NULL, accuracy = NA, f1 = FALSE)),
    xpectr::strip("Assertion on 'accuracy' failed: May not be NA."),
    fixed = TRUE)

  # Testing get_metric_names(all = NULL, accuracy = NULL, ...
  # Assigning output
  output_12016 <- get_metric_names(all = NULL, accuracy = NULL, f1 = FALSE)
  # Testing class
  expect_equal(
    class(output_12016),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_12016,
    type = "character")
  # Testing values
  expect_equal(
    output_12016,
    c("Balanced Accuracy", "Sensitivity", "Specificity", "Pos Pred Value",
      "Neg Pred Value", "AUC", "Lower CI", "Upper CI", "Kappa",
      "MCC", "Detection Rate", "Detection Prevalence", "Prevalence"),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_12016),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_12016),
    13L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_12016)),
    13L)

  # Testing get_metric_names(all = NULL, accuracy = FALSE,...
  # Assigning output
  output_18982 <- get_metric_names(all = NULL, accuracy = FALSE, f1 = FALSE)
  # Testing class
  expect_equal(
    class(output_18982),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_18982,
    type = "character")
  # Testing values
  expect_equal(
    output_18982,
    c("Balanced Accuracy", "Sensitivity", "Specificity", "Pos Pred Value",
      "Neg Pred Value", "AUC", "Lower CI", "Upper CI", "Kappa",
      "MCC", "Detection Rate", "Detection Prevalence", "Prevalence"),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_18982),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_18982),
    13L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_18982)),
    13L)

  # Testing get_metric_names(all = NULL, accuracy = FALSE,...
  # Assigning output
  output_19445 <- get_metric_names(all = NULL, accuracy = FALSE, f1 = NULL)
  # Testing class
  expect_equal(
    class(output_19445),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_19445,
    type = "character")
  # Testing values
  expect_equal(
    output_19445,
    c("Balanced Accuracy", "F1", "Sensitivity", "Specificity", "Pos Pred Value",
      "Neg Pred Value", "AUC", "Lower CI", "Upper CI", "Kappa",
      "MCC", "Detection Rate", "Detection Prevalence", "Prevalence"),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_19445),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_19445),
    14L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_19445)),
    14L)

  ## Finished testing 'get_metric_names'                                      ####


  ## Testing 'get_metric_names(all = TRUE)'                                 ####
  ## Initially generated by xpectr
  # Assigning output
  output_16607 <- get_metric_names(all = TRUE)
  # Testing class
  expect_equal(
    class(output_16607),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_16607,
    type = "character")
  # Testing values
  expect_equal(
    output_16607,
    c("Balanced Accuracy", "Accuracy", "F1", "Sensitivity", "Specificity",
      "Pos Pred Value", "Neg Pred Value", "AUC", "Lower CI", "Upper CI",
      "Kappa", "MCC", "Detection Rate", "Detection Prevalence",
      "Prevalence", "False Neg Rate", "False Pos Rate", "False Discovery Rate",
      "False Omission Rate", "Threat Score", "AIC", "AICc", "BIC"),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_16607),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_16607),
    23L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_16607)),
    23L)
  ## Finished testing 'get_metric_names(all = TRUE)'                        ####

})

test_that("binomial_metrics()", {

  # Load data and fold it
  xpectr::set_test_seed(1)

  get_metric_names <- function(...){
    set_metrics("multinomial", metrics_list = multinomial_metrics(...),
                include_model_object_metrics = TRUE)
  }

  # xpectr::gxs_function(fn = get_metric_names,
  #                      args_values = list(
  #                        all = list(NULL,FALSE, TRUE, NA, 1, 0, "hej", list(FALSE)),
  #                        accuracy = list(FALSE, TRUE, NA),
  #                        f1 = list(FALSE, TRUE, NA)
  #                      ), indentation = 2)

  ## Testing 'get_metric_names'                                               ####
  ## Initially generated by xpectr
  # Testing different combinations of argument values

  # Testing get_metric_names(all = FALSE, accuracy = FALSE...
  # Assigning output
  output_17375 <- get_metric_names(all = FALSE, accuracy = FALSE, f1 = FALSE)
  # Testing class
  expect_equal(
    class(output_17375),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_17375,
    type = "character")
  # Testing values
  expect_equal(
    output_17375,
    character(0),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_17375),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_17375),
    0L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_17375)),
    0L)

  # Testing get_metric_names(all = NULL, accuracy = FALSE,...
  # Assigning output
  output_18109 <- get_metric_names(all = NULL, accuracy = FALSE, f1 = TRUE)
  # Testing class
  expect_equal(
    class(output_18109),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_18109,
    type = "character")
  # Testing values
  expect_equal(
    output_18109,
    c("Overall Accuracy", "Balanced Accuracy", "F1", "Sensitivity",
      "Specificity", "Pos Pred Value", "Neg Pred Value", "Kappa",
      "MCC", "Detection Rate", "Detection Prevalence", "Prevalence"),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_18109),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_18109),
    12L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_18109)),
    12L)

  # Testing get_metric_names(all = NULL, accuracy = FALSE,...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(get_metric_names(all = NULL, accuracy = FALSE, f1 = NA)),
    xpectr::strip("Assertion on 'f1' failed: May not be NA."),
    fixed = TRUE)

  # Testing get_metric_names(all = TRUE, accuracy = FALSE,...
  # Assigning output
  output_13880 <- get_metric_names(all = TRUE, accuracy = FALSE, f1 = FALSE)
  # Testing class
  expect_equal(
    class(output_13880),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_13880,
    type = "character")
  # Testing values
  expect_equal(
    xpectr::smpl(output_13880, n = 30),
    c("Balanced Accuracy", "Weighted Balanced Accuracy", "Weighted F1",
      "Weighted Sensitivity", "Pos Pred Value", "Weighted Pos Pred Value",
      "Neg Pred Value", "Weighted Neg Pred Value", "AUC", "Kappa",
      "Weighted Kappa", "MCC", "Weighted MCC", "Detection Rate",
      "Weighted Detection Rate", "Detection Prevalence", "Weighted Detection Prevalence",
      "Prevalence", "Weighted Prevalence", "False Neg Rate", "Weighted False Neg Rate",
      "Weighted False Pos Rate", "False Discovery Rate", "Weighted False Discovery Rate",
      "False Omission Rate", "Threat Score", "Weighted Threat Score",
      "AIC", "AICc", "BIC"),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(xpectr::smpl(output_13880, n = 30)),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_13880),
    37L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_13880)),
    37L)

  # Testing get_metric_names(all = NA, accuracy = FALSE, f...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(get_metric_names(all = NA, accuracy = FALSE, f1 = FALSE)),
    xpectr::strip("Assertion on 'all' failed: May not be NA."),
    fixed = TRUE)

  # Testing get_metric_names(all = 1, accuracy = FALSE, f1...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(get_metric_names(all = 1, accuracy = FALSE, f1 = FALSE)),
    xpectr::strip(paste0("Assertion on 'all' failed: Must be of type 'logical flag' (o",
           "r 'NULL'), not 'double'.")),
    fixed = TRUE)

  # Testing get_metric_names(all = 0, accuracy = FALSE, f1...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(get_metric_names(all = 0, accuracy = FALSE, f1 = FALSE)),
    xpectr::strip(paste0("Assertion on 'all' failed: Must be of type 'logical flag' (o",
           "r 'NULL'), not 'double'.")),
    fixed = TRUE)

  # Testing get_metric_names(all = "hej", accuracy = FALSE...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(get_metric_names(all = "hej", accuracy = FALSE, f1 = FALSE)),
    xpectr::strip(paste0("Assertion on 'all' failed: Must be of type 'logical flag' (o",
           "r 'NULL'), not 'character'.")),
    fixed = TRUE)

  # Testing get_metric_names(all = list(FALSE), accuracy =...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(get_metric_names(all = list(FALSE), accuracy = FALSE, f1 = FALSE)),
    xpectr::strip(paste0("Assertion on 'all' failed: Must be of type 'logical flag' (o",
           "r 'NULL'), not 'list'.")),
    fixed = TRUE)

  # Testing get_metric_names(all = NULL, accuracy = TRUE, ...
  # Assigning output
  output_17375 <- get_metric_names(all = NULL, accuracy = TRUE, f1 = FALSE)
  # Testing class
  expect_equal(
    class(output_17375),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_17375,
    type = "character")
  # Testing values
  expect_equal(
    output_17375,
    c("Overall Accuracy", "Balanced Accuracy", "Accuracy", "Sensitivity",
      "Specificity", "Pos Pred Value", "Neg Pred Value", "Kappa",
      "MCC", "Detection Rate", "Detection Prevalence", "Prevalence"),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_17375),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_17375),
    12L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_17375)),
    12L)

  # Testing get_metric_names(all = NULL, accuracy = NA, f1...
  # Testing side effects
  expect_error(
    xpectr::strip_msg(get_metric_names(all = NULL, accuracy = NA, f1 = FALSE)),
    xpectr::strip("Assertion on 'accuracy' failed: May not be NA."),
    fixed = TRUE)

  # Testing get_metric_names(all = NULL, accuracy = NULL, ...
  # Assigning output
  output_18109 <- get_metric_names(all = NULL, accuracy = NULL, f1 = FALSE)
  # Testing class
  expect_equal(
    class(output_18109),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_18109,
    type = "character")
  # Testing values
  expect_equal(
    output_18109,
    c("Overall Accuracy", "Balanced Accuracy", "Sensitivity", "Specificity",
      "Pos Pred Value", "Neg Pred Value", "Kappa", "MCC", "Detection Rate",
      "Detection Prevalence", "Prevalence"),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_18109),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_18109),
    11L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_18109)),
    11L)

  # Testing get_metric_names(all = NULL, accuracy = FALSE,...
  # Assigning output
  output_13880 <- get_metric_names(all = NULL, accuracy = FALSE, f1 = FALSE)
  # Testing class
  expect_equal(
    class(output_13880),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_13880,
    type = "character")
  # Testing values
  expect_equal(
    output_13880,
    c("Overall Accuracy", "Balanced Accuracy", "Sensitivity", "Specificity",
      "Pos Pred Value", "Neg Pred Value", "Kappa", "MCC", "Detection Rate",
      "Detection Prevalence", "Prevalence"),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_13880),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_13880),
    11L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_13880)),
    11L)

  # Testing get_metric_names(all = NULL, accuracy = FALSE,...
  # Assigning output
  output_16851 <- get_metric_names(all = NULL, accuracy = FALSE, f1 = NULL)
  # Testing class
  expect_equal(
    class(output_16851),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_16851,
    type = "character")
  # Testing values
  expect_equal(
    output_16851,
    c("Overall Accuracy", "Balanced Accuracy", "F1", "Sensitivity",
      "Specificity", "Pos Pred Value", "Neg Pred Value", "Kappa",
      "MCC", "Detection Rate", "Detection Prevalence", "Prevalence"),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_16851),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_16851),
    12L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_16851)),
    12L)

  ## Finished testing 'get_metric_names'                                      ####



  ## Testing 'get_metric_names(all = TRUE)'                                 ####
  ## Initially generated by xpectr
  # Assigning output
  output_12654 <- get_metric_names(all = TRUE)
  # Testing class
  expect_equal(
    class(output_12654),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_12654,
    type = "character")
  # Testing values
  expect_equal(
    xpectr::smpl(output_12654, n = 30),
    c("Balanced Accuracy", "Weighted Balanced Accuracy", "Weighted Accuracy",
      "F1", "Weighted F1", "Sensitivity", "Weighted Sensitivity",
      "Specificity", "Weighted Specificity", "Pos Pred Value", "Neg Pred Value",
      "AUC", "Kappa", "Weighted Kappa", "Detection Rate", "Weighted Detection Rate",
      "Detection Prevalence", "Weighted Detection Prevalence", "Prevalence",
      "Weighted Prevalence", "Weighted False Pos Rate", "False Discovery Rate",
      "Weighted False Discovery Rate", "False Omission Rate", "Weighted False Omission Rate",
      "Threat Score", "Weighted Threat Score", "AIC", "AICc", "BIC"),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(xpectr::smpl(output_12654, n = 30)),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_12654),
    39L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_12654)),
    39L)
  ## Finished testing 'get_metric_names(all = TRUE)'                        ####

})

