validate_list <- function(train_data,
                          formulas,
                          model_fn,
                          predict_fn,
                          preprocess_fn = NULL,
                          preprocess_once = FALSE,
                          hyperparameters = NULL,
                          fold_cols = '.folds',
                          family = 'gaussian',
                          cutoff = 0.5,
                          positive = 2,
                          metrics = list(),
                          err_nc = FALSE,
                          rm_nc = FALSE,
                          test_data = NULL,
                          partitions_col = '.partitions',
                          model_verbose = FALSE,
                          parallel_ = FALSE) {
}
